// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gT-40yB79CeTfER1QDpcPMfQ62JtnWA',
    appId: '1:719513005022:web:bdd640be3c19e03198cb4f',
    messagingSenderId: '719513005022',
    projectId: 'event-management-app-48d30',
    authDomain: 'event-management-app-48d30.firebaseapp.com',
    storageBucket: 'event-management-app-48d30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB43MzdJ_PGxfM3CmnmIT46uZZ4O_TL60g',
    appId: '1:719513005022:android:919f3330a6a061cd98cb4f',
    messagingSenderId: '719513005022',
    projectId: 'event-management-app-48d30',
    storageBucket: 'event-management-app-48d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0YpIv51uYnmdp8x5H11ifPcq0BdrCkQ',
    appId: '1:719513005022:ios:61ccee2212de496c98cb4f',
    messagingSenderId: '719513005022',
    projectId: 'event-management-app-48d30',
    storageBucket: 'event-management-app-48d30.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0YpIv51uYnmdp8x5H11ifPcq0BdrCkQ',
    appId: '1:719513005022:ios:61ccee2212de496c98cb4f',
    messagingSenderId: '719513005022',
    projectId: 'event-management-app-48d30',
    storageBucket: 'event-management-app-48d30.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5gT-40yB79CeTfER1QDpcPMfQ62JtnWA',
    appId: '1:719513005022:web:6f5b66984093b6de98cb4f',
    messagingSenderId: '719513005022',
    projectId: 'event-management-app-48d30',
    authDomain: 'event-management-app-48d30.firebaseapp.com',
    storageBucket: 'event-management-app-48d30.firebasestorage.app',
  );
}
